# roles/ROLENAME/tasks/main.yml
---
- name: "Include {{ ansible_distribution }} variables"
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"
  tags: install

- name: Create the 'openio' group
  group:
    name: openio
    gid: "{{ openio_group_openio_gid | default('220')}}"
  tags: install

- name: Create the 'openio' user
  user:
    name: openio
    comment: "openio account"
    uid: "{{ openio_user_openio_uid | default('120')}}"
    group: openio
  tags: install

- name: "Include {{ ansible_distribution }} tasks"
  include_tasks: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"
  tags: install

- name: Generate configuration files
  template:
    src: ROLENAME.conf.j2
    dest: "/etc/oio/sds/{{ openio_ROLENAME_namespace }}/..."
    owner: openio
    group: openio
    mode: 0644
  tags: install
  register: _ROLENAME_conf


- name: restart ROLENAME
  command: "gridinit_cmd restart  {{openio_ROLENAME_namespace}}-ROLENAME-{{openio_ROLENAME_serviceid}}"
  when: _ROLENAME_conf.changed
  tags: configure
...
